# [vagrant@zabbix vagrant]$ ansible-playbook playbook.yml -i localhost, --connection=local

---
- hosts: all
  become: true
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: upgrade all packages
      yum:
        name: https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64/zabbix-release-4.4-1.el7.noarch.rpm
        state: latest
        update_cache: yes

---
- hosts: zabbix
  become: true
  tasks:
    - name: Install zabbix packages
      package:
        state: installed
        name:
          - zabbix-server-mysql
          - zabbix-web-mysql
          - zabbix-nginx-conf
          - zabbix-agent
          - mariadb
          - mariadb-server
          - MySQL-python
          - vim
          - ansible

    - name: Edit nginx configuration (hostname and listen)
      blockinfile:
        dest: /etc/nginx/conf.d/zabbix.conf
        insertafter: "^server {"
        block: |
          listen          80;
          server_name     zabbix.local;

    - name: Edit php-fpm configuration (timezone)
      lineinfile:
        dest: /etc/php-fpm.d/zabbix.conf
        line: "php_value[date.timezone] = Europe/Amsterdam"

    - name: Start services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - mariadb
        - nginx
        - zabbix-agent
        - zabbix-server
        - php-fpm

    #- name: gunzip file
    #  command: gunzip /usr/share/doc/zabbix-server-mysql-4.4.0/create.sql.gz
    #  args:
    #    creates: /usr/share/doc/zabbix-server-mysql-4.4.0/create.sql

    - name: Make DB
      mysql_db:
        state: present
        name: zabbix
        collation: utf8_bin
        encoding: utf8
      register: createdb

    - name: Import DB
      mysql_db:
        state: import
        name: zabbix
        collation: utf8_bin
        encoding: utf8
        target: /usr/share/doc/zabbix-server-mysql-4.4.0/create.sql.gz
      when: createdb is changed

    - name: Make DB user
      mysql_user:
        name: zabbix
        priv: "zabbix.*:ALL"
        state: present

    - name: Login
      debug:
        msg: "Login op http://zabbix.local met Admin / zabbix"
